name: PKG

on:
  push:
    branches: ['master']
    tags: ['*']
  workflow_dispatch: {}

env:
  app_image: seboknt/ui

  should_push_image: |-
    ${{
      github.event_name == 'push' && (
        github.ref_type == 'tag' ||
        github.ref_name == 'master'
      )
    }}

  should_tag_latest: |-
    ${{
      github.event_name == 'push' &&
      github.ref_type == 'tag'
    }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Prep build and fill cache
        run: | 
          docker buildx create --use
          docker buildx build --platform linux/amd64,linux/arm64 -f Dockerfile -t $app_image:${GIT_COMMIT_SHORT_HASH:-dev} .
        
      - name: Login container registry
        if: fromJSON(env.should_push_image)
        run: |
          echo "${{ secrets.REGISTRY_PASSWORD }}" \
            | docker login -u "${{ secrets.REGISTRY_USER }}" --password-stdin

      - name: Build & Push
        if: fromJSON(env.should_push_image)
        run: |
          safe_ref=$(echo "${{ github.ref_name }}" | sed -e 's/[^a-zA-Z0-9\-\.]/-/g')
          docker buildx build --push --platform linux/amd64,linux/arm64 -f Dockerfile -t $app_image:$safe_ref .

      - name: Push latest
        if: fromJSON(env.should_tag_latest)
        run: |
          docker buildx build --push --platform linux/amd64,linux/arm64 -f Dockerfile -t $app_image:latest .
